import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, Search, ShieldCheck, Sparkles } from "lucide-react";
import PublicHeader from "@/components/shared/PublicHeader";
import GlobalFooter from "@/components/shared/GlobalFooter";
import { skills, certificationSteps } from "@/lib/skillsData";

export const metadata = {
  title: "ASSISTLANA Skills | Free Learning and Skill Certification",
  description: "Learn practical skills for free, practise with clear lessons, and take a skill-based assessment for a digital certificate.",
  alternates: { canonical: "https://assistlana-website-6fzh.vercel.app/skills" },
};

const questions = [
  ["What is Python?", "/skills/python-fundamentals"],
  ["What is SQL?", "/skills/sql-fundamentals"],
  ["What is digital marketing?", "/skills/digital-marketing-fundamentals"],
  ["What is artificial intelligence?", "/skills/artificial-intelligence-fundamentals"],
  ["How do I get a skill certificate?", "#certification"],
];

export default function SkillsPage() {
  const grouped = skills.reduce((groups, skill) => {
    groups[skill.category] = [...(groups[skill.category] || []), skill];
    return groups;
  }, {});

  const schema = {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: "ASSISTLANA Skills",
    description: "Free learning paths and skill-based assessments.",
    itemListElement: skills.map((skill, index) => ({ "@type": "ListItem", position: index + 1, name: skill.name, url: `https://assistlana-website-6fzh.vercel.app/skills/${skill.slug}` })),
  };

  return (
    <div className="min-h-screen bg-[#f6f8fc] text-[#10213b]">
      <PublicHeader />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <main>
        <section className="relative overflow-hidden bg-[#10213b] text-white">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_76%_18%,rgba(37,99,235,.45),transparent_35%),radial-gradient(circle_at_18%_100%,rgba(6,182,212,.2),transparent_30%)]" />
          <div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-20 md:grid-cols-[1.1fr_.9fr] md:px-8 md:py-28">
            <div>
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-300/30 bg-white/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.18em] text-cyan-200"><Sparkles size={14} /> ASSISTLANA Skills</div>
              <h1 className="max-w-3xl text-4xl font-black leading-[1.05] tracking-tight md:text-6xl">Learn free. Prove your skills. Get certified.</h1>
              <p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 md:text-lg">Learn practical skills through free learning resources, test your knowledge with a skill-based assessment, and earn a digital certificate when you pass.</p>
              <div className="mt-9 flex flex-wrap gap-3">
                <a href="#catalog" className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-[#10213b] hover:bg-cyan-300">Explore skills <ArrowRight size={16} /></a>
                <a href="#certification" className="inline-flex items-center gap-2 rounded-xl border border-white/20 px-5 py-3 text-sm font-bold text-white hover:bg-white/10">How certification works</a>
              </div>
            </div>
            <div className="self-end rounded-[2rem] border border-white/10 bg-white/[.08] p-6 backdrop-blur">
              <div className="mb-6 text-xs font-bold uppercase tracking-[.2em] text-cyan-200">Your learning path</div>
              <div className="space-y-3">
                {["Learn", "Practise", "Assess", "Certify"].map((step, index) => <div key={step} className="flex items-center gap-4 rounded-2xl bg-white/[.08] p-4"><span className="grid h-9 w-9 place-items-center rounded-full bg-cyan-300 font-black text-[#10213b]">{index + 1}</span><span className="text-lg font-bold">{step}</span>{index < 3 && <span className="ml-auto text-cyan-200">↓</span>}</div>)}
              </div>
              <p className="mt-5 text-sm leading-6 text-slate-300">Assessment settings: 30 questions, 30 minutes, 75% passing score. Browser-based monitoring is disclosed before you begin.</p>
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-7xl px-5 py-16 md:px-8">
          <div className="grid gap-5 md:grid-cols-3">
            {[[BookOpen, "Free learning", "Question-led lessons with definitions, examples, practice tasks, and interview prompts."], [CheckCircle2, "Skill assessment", "A focused assessment for the skill you selected, with your answers sent to the backend for scoring."], [ShieldCheck, "Digital certificate", "Qualifying candidates can receive a certificate generated by the connected certification backend."]].map(([Icon, title, text]) => <div key={title} className="border-l-2 border-cyan-400 pl-5"><Icon className="mb-4 text-blue-600" size={22} /><h2 className="text-lg font-extrabold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div>)}
          </div>
        </section>

        <section id="catalog" className="scroll-mt-20 border-y border-slate-200 bg-white">
          <div className="mx-auto max-w-7xl px-5 py-16 md:px-8">
            <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Choose your path</p><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">Skills built for useful progress</h2><p className="mt-3 max-w-2xl text-slate-600">Start with a beginner-friendly foundation. Every path connects explanations to practice and certification.</p></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-500"><Search size={16} /> Search is coming to the catalog</div></div>
            <div className="mt-12 space-y-12">{Object.entries(grouped).map(([category, categorySkills]) => <div key={category}><h3 className="mb-5 text-sm font-bold uppercase tracking-[.18em] text-slate-500">{category}</h3><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{categorySkills.map(skill => <article key={skill.slug} className="group flex min-h-[220px] flex-col border border-slate-200 bg-[#fbfcff] p-5 transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-xl hover:shadow-blue-900/5"><div className="flex items-center justify-between"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{skill.level}</span><span className="text-xs text-slate-400">{skill.duration}</span></div><h4 className="mt-5 text-xl font-extrabold group-hover:text-blue-700">{skill.name}</h4><p className="mt-2 flex-1 text-sm leading-6 text-slate-600">{skill.description}</p><div className="mt-5 flex items-center gap-4 text-sm font-bold"><Link href={`/skills/${skill.slug}`} className="text-blue-700 hover:text-blue-900">Start learning <ArrowRight className="ml-1 inline" size={15} /></Link><Link href={`/skills/${skill.slug}#assessment`} className="text-slate-500 hover:text-blue-700">Get certified</Link></div></article>)}</div></div>)}</div>
          </div>
        </section>

        <section className="mx-auto max-w-7xl px-5 py-16 md:px-8"><div className="grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Popular questions</p><h2 className="mt-3 text-3xl font-black">Get a direct answer, then go deeper.</h2><p className="mt-4 leading-7 text-slate-600">Each skill page begins with short answers and links those answers to a practical learning path.</p></div><div className="grid gap-3 sm:grid-cols-2">{questions.map(([question, href]) => <Link key={question} href={href} className="flex items-center justify-between border border-slate-200 bg-white p-4 text-sm font-bold hover:border-blue-300 hover:text-blue-700">{question}<ArrowRight size={16} /></Link>)}</div></div></section>

        <section id="certification" className="bg-[#10213b] text-white"><div className="mx-auto max-w-7xl px-5 py-16 md:px-8"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Free skill certification</p><h2 className="mt-3 text-3xl font-black md:text-4xl">A clear path from learning to proof.</h2><p className="mt-4 leading-7 text-slate-300">Choose a skill, learn the material, register, and complete its assessment. The backend decides the result and handles certificate generation for qualifying candidates.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{certificationSteps.map(([number, title, text]) => <div key={number} className="border border-white/10 bg-white/[.06] p-5"><span className="text-sm font-black text-cyan-300">{number}</span><h3 className="mt-8 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{text}</p></div>)}</div></div></section>
      </main>
      <GlobalFooter />
    </div>
  );
}
