"use client";

import Link from "next/link";
import { ArrowRight, Bot, Brain, BriefcaseBusiness, CheckCircle2, Code2, Database, FileSearch, Layers3, Network, Rocket, Sparkles, Workflow } from "lucide-react";
import PublicHeader from "@/components/shared/PublicHeader";
import GlobalFooter from "@/components/shared/GlobalFooter";
import { FAQSchema, SoftwareApplicationSchema, FAQ_ITEMS } from "@/components/StructuredData";

const products = [
  ["AI Resume Screening", "Rank and review candidate resumes with intelligent matching.", FileSearch, "/products#ai-resume-screening"],
  ["AI Resume Optimizer", "Give candidates clear, AI-powered resume improvement guidance.", Brain, "/products#ai-resume-optimizer"],
  ["AI Job Match", "Connect talent and opportunities with smarter matching.", Network, "/products#ai-job-match"],
  ["ATS Resume Checker", "Check resumes for ATS-readiness before submission.", CheckCircle2, "/products#ats-checker"],
  ["AI Agent Builder", "Create intelligent agents for multi-step business tasks.", Bot, "/products#ai-agent-builder"],
  ["AI Workflow Automation", "Turn repeatable work into dependable automated workflows.", Workflow, "/products#ai-workflow"],
];
const capabilities = [["AI Product Development", "From concept to a scalable, usable AI product."], ["Custom AI Software", "Built around your workflows, data and business goals."], ["Enterprise SaaS", "Reliable software platforms for teams that need to scale."], ["Business Automation", "Reduce manual work and keep operations moving."]];

export default function HomePage() {
  return <div className="min-h-screen bg-white text-[#0F172A]"><PublicHeader /><main>
    <section className="relative isolate overflow-hidden bg-[#091426] px-5 py-20 text-white md:px-8 md:py-28">
      <div className="absolute inset-0 -z-10 opacity-60" style={{ backgroundImage: "radial-gradient(circle at 15% 15%, rgba(6,182,212,.3), transparent 24rem), radial-gradient(circle at 85% 65%, rgba(37,99,235,.38), transparent 26rem)" }} />
      <div className="absolute inset-0 -z-10 opacity-20" style={{ backgroundImage: "radial-gradient(rgba(255,255,255,.55) 1px, transparent 1px)", backgroundSize: "28px 28px" }} />
      <div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="inline-flex items-center gap-2 rounded-full border border-cyan-300/30 bg-cyan-300/10 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-cyan-200"><Sparkles size={14}/> AI Products • Automation • Enterprise SaaS</p><h1 className="mt-6 max-w-4xl text-4xl font-black leading-[1.05] tracking-tight md:text-6xl">Building intelligent AI products for modern businesses.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 md:text-lg">ASSISTLANA builds AI-powered products, intelligent agents, workflow automation platforms, and enterprise SaaS solutions that help businesses work smarter and scale faster.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3.5 text-sm font-bold text-slate-950 hover:bg-cyan-200">Explore AI Products <ArrowRight size={16}/></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/5 px-5 py-3.5 text-sm font-bold text-white hover:bg-white/10">Build With ASSISTLANA <ArrowRight size={16}/></Link></div></div><div className="grid grid-cols-2 gap-3 sm:gap-4">{[[Bot,"AI Agents"],[Workflow,"Automation"],[Layers3,"Enterprise SaaS"],[Code2,"Custom Software"]].map(([Icon,label]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.07] p-5 backdrop-blur-sm"><Icon size={24} className="text-cyan-300"/><p className="mt-8 text-base font-bold">{label}</p><p className="mt-1 text-sm text-slate-300">Designed for modern operations.</p></div>)}</div></div>
    </section>
    <section className="px-5 py-18 md:px-8 md:py-24" id="products"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">AI product suite</p><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">Intelligence that fits the way your business works.</h2><p className="mt-4 leading-7 text-slate-600">Practical AI software for talent, operations and the workflows in between.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{products.map(([title, text, Icon, href]) => <Link key={title} href={href} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-blue-300 hover:shadow-lg"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon size={21}/></div><h3 className="mt-6 font-extrabold group-hover:text-blue-700">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-blue-700">Explore <ArrowRight size={15}/></span></Link>)}</div></div></section>
    <section className="bg-slate-50 px-5 py-18 md:px-8 md:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-600">Built for outcomes</p><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">From ambitious idea to dependable business system.</h2><p className="mt-4 leading-7 text-slate-600">We combine product thinking, AI expertise and software engineering to help teams build the next useful thing.</p><Link href="/solutions" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#0F172A] px-5 py-3 text-sm font-bold text-white hover:bg-slate-800">Explore solutions <ArrowRight size={16}/></Link></div><div className="grid gap-4 sm:grid-cols-2">{capabilities.map(([title,text], index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6"><span className="text-sm font-black text-teal-600">0{index + 1}</span><h3 className="mt-8 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="px-5 py-18 md:px-8 md:py-24"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-2"><article className="rounded-3xl bg-gradient-to-br from-[#10213B] to-[#164e63] p-7 text-white md:p-10"><BriefcaseBusiness className="text-cyan-300" size={28}/><p className="mt-7 text-xs font-bold uppercase tracking-[.18em] text-cyan-200">ASSISTLANA internships</p><h2 className="mt-3 text-3xl font-black">Build real-world experience.</h2><p className="mt-4 max-w-xl leading-7 text-slate-300">Join ASSISTLANA internships and gain practical experience by working on technology, AI, software, business and digital projects.</p><div className="mt-6 flex flex-wrap gap-2">{["Tech + Non-Tech Opportunities","Work From Home Opportunities","Opportunities Across India","Students & Freshers"].map(x => <span key={x} className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold">{x}</span>)}</div><Link href="/apply" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-slate-900">Explore Internships <ArrowRight size={16}/></Link></article><article className="rounded-3xl border border-blue-100 bg-gradient-to-br from-blue-50 to-cyan-50 p-7 md:p-10"><Database className="text-blue-600" size={28}/><p className="mt-7 text-xs font-bold uppercase tracking-[.18em] text-blue-600">Learning initiative</p><h2 className="mt-3 text-3xl font-black">Learn skills. Get certified.</h2><p className="mt-4 max-w-xl leading-7 text-slate-600">Build practical technology and professional skills through beginner-friendly learning paths, assessments and free certificates.</p><div className="mt-6 flex flex-wrap gap-2">{["FREE LEARNING","FREE SKILL ASSESSMENT","FREE CERTIFICATE"].map(x => <span key={x} className="rounded-full border border-blue-200 bg-white px-3 py-1.5 text-xs font-bold text-blue-700">{x}</span>)}</div><div className="mt-7 flex flex-wrap gap-3"><Link href="/skills" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white hover:bg-blue-700">Explore Free Learning <ArrowRight size={16}/></Link><Link href="/skills#certification" className="inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-white px-5 py-3 text-sm font-bold text-blue-700">Get Your Free Certificate</Link></div></article></div></section>
    <section className="bg-[#0b1930] px-5 py-18 text-white md:px-8 md:py-24"><div className="mx-auto max-w-3xl text-center"><Rocket className="mx-auto text-cyan-300" size={30}/><h2 className="mt-5 text-3xl font-black md:text-4xl">Ready to build an intelligent advantage?</h2><p className="mt-4 text-slate-300">Bring us the workflow, challenge or product idea. We’ll help shape the AI solution.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3.5 text-sm font-bold text-slate-950 hover:bg-cyan-200">Talk to ASSISTLANA <ArrowRight size={16}/></Link></div></section>
  </main><FAQSchema items={FAQ_ITEMS}/><SoftwareApplicationSchema/><GlobalFooter /></div>;
}
